import argparse
import json
import os
import platform
import queue
import re
import subprocess
import sys
import threading
import time
from collections import deque
from datetime import datetime
from pathlib import Path
from tkinter import BOTH, END, LEFT, RIGHT, X, Button, Canvas, Checkbutton, Entry, Frame, Label, Listbox, PhotoImage, StringVar, Text, Tk, filedialog, ttk

import psutil

from game_profiles import PROFILES
from geometry_json import RECTANGLE, ROTATED_ELLIPSE, load_normalized_geometry
from generator_backend import GENERATOR_EXE, best_geometry_jsons, build_generator_command, generated_jsons, generated_preview_files, generator_preview_path, load_settings, write_custom_settings
from version import APP_DISPLAY_NAME, __version__, app_title


APP_DIR = Path(__file__).resolve().parent
ROOT = APP_DIR.parent
PROBE_DIR = ROOT / "webui-data" / "probes"
SESSION_PATH = PROBE_DIR / "current-fh6-session.json"
MEMORY_SNAPSHOT_LIMIT_MB = 2048
PREVIEW_MAX = 520
DETAILED_LOG_OUTPUT_LIMIT = 50000
DETAILED_LOG_MEMORY_LIMIT = 120000
FH6_AUTO_LOCATE_MAX_SECONDS = 120
FH6_AUTO_LOCATE_TIMEOUT_SECONDS = 160
_CV2_CACHE = None
_CV2_ERROR = None

LANGUAGES = {
    "English": "en",
    "中文": "zh",
    "한국어": "ko",
}


TEXT = {
    "en": {
        "title": app_title(),
        "subtitle": "Generate geometry JSON and import it into Forza Horizon vinyl editor.",
        "language": "Language",
        "process": "Game process",
        "refresh": "Refresh",
        "generate_tab": "Generate JSON",
        "import_tab": "Import",
        "tools_tab": "FH6 Tools",
        "tutorial_tab": "Tutorial",
        "images": "Images",
        "add_images": "Add images",
        "quality": "Quality profile",
        "custom_settings": "Use custom settings",
        "custom_layers": "Output layers",
        "custom_resolution": "Max resolution",
        "custom_random": "Random samples",
        "custom_mutated": "Mutated samples",
        "custom_save_at": "Save checkpoints",
        "custom_panel_title": "Custom settings",
        "custom_panel_hint": "The selected preset fills these values. Enable custom settings if you want to edit them before generating.",
        "generate_step_image": "Step 1 - Choose images",
        "generate_step_image_hint": "Add PNG/JPG/BMP images. Generated JSON is saved beside each source image.",
        "generate_step_quality": "Step 2 - Choose quality",
        "generate_step_quality_hint": "Fast profiles are quicker. Slow profiles use more GPU time and usually look cleaner.",
        "generate_step_run": "Step 3 - Generate",
        "generate_step_run_hint": "Click once and wait. Progress appears in Logs; generated JSON is added to the Import page automatically.",
        "scroll_hint": "Add image, choose a preset, then adjust custom settings if needed.",
        "start_generate": "Generate with current settings",
        "stop_generate": "Stop current generation",
        "open_output": "Open output folder",
        "preview": "Preview",
        "preview_hint": "Select an image or JSON to preview it here.",
        "preview_unavailable": "Preview is unavailable. Install optional preview dependencies, or continue without preview.",
        "logs": "Logs",
        "export_logs": "Export detailed log",
        "progress": "Progress",
        "json_files": "Geometry JSON files",
        "add_json": "Add JSON",
        "use_outputs": "Use generated JSON",
        "step_game": "Step 1 - Game",
        "step_game_hint": "Start FH6, open Vinyl Group Editor, load an ungrouped sphere template, then refresh the process list.",
        "step_template": "Step 2 - Template",
        "step_template_hint": "Enter the exact layer count shown by your current in-game template.",
        "step_json": "Step 3 - JSON",
        "step_json_hint": "Use the JSON generated by this app, or add a geometry JSON manually.",
        "step_import": "Step 4 - Import",
        "step_import_hint": "Click import once. The app will find the FH6 layer table safely, then write the design.",
        "advanced_options": "Advanced options",
        "show_advanced": "Show advanced",
        "hide_advanced": "Hide advanced",
        "import_preview": "Selected JSON preview",
        "game_profile": "Game profile",
        "pid": "PID",
        "layer_count": "Template layer count",
        "easy_import": "Easy import",
        "easy_import_hint": "For FH6, leave addresses empty. The app will reuse a live session or auto-locate before import.",
        "manual_count": "Layer count address",
        "manual_table": "Layer table address",
        "auto_locate": "Auto-locate FH6",
        "import_json": "Import JSON",
        "diagnose": "Diagnose",
        "save_snapshot": "Save count snapshot",
        "compare_snapshot": "Compare snapshot",
        "snapshot_count": "Snapshot layer count",
        "current_count": "Current layer count",
        "inspect_table": "Inspect table",
        "table_address": "Candidate table",
        "admin_note": "Import needs administrator permission. Start this app as administrator if OpenProcess fails.",
        "no_game": "No supported game process detected",
        "ready": "Ready",
        "running": "Running",
        "done": "Done",
        "failed": "Failed",
        "stopped": "Stopped",
        "no_generation_running": "No generation is running.",
        "stopping_generation": "Stopping current generation...",
        "generation_stopped": "Generation stopped.",
        "locating": "Finding current FH6 template...",
        "located": "FH6 template located and verified.",
        "importing": "Importing JSON into FH6...",
        "json_too_small": "Selected JSON has far fewer drawable layers than the usable template capacity. Import will look blurry; choose a higher-layer JSON.",
        "json_needs_more_template_layers": "FH needs 4 boundary layers for correct cover/apply behavior. Use a template with at least JSON drawable layers + 4.",
        "safe_stop": "Stopped before writing because no safe FH6 template was found.",
        "tutorial": """Beginner workflow

1. Install 64-bit Python 3.12 if possible, then run install_dependencies.bat.
   NumPy/OpenCV preview is optional; generation and import do not require it.
   JSON generation uses the bundled GPU/OpenCL generator, so keep the graphics driver updated.

2. Start Forza Horizon 6 and enter Create Vinyl Group / Vinyl Group Editor.

3. Load or create a template made of many simple sphere layers. 500 or more layers is recommended. Ungroup the template before importing.

4. In this app, open Generate JSON, add a PNG/JPG/BMP image, choose a quality profile, then click Start generating. If preview dependencies are available, the preview area shows the source image first, then the generated geometry preview when JSON appears.

5. Open Import. Add the generated JSON or click Use generated JSON. Keep Game profile as Forza Horizon 6.

6. Enter the real template layer count currently loaded in-game. For FH6 you normally do not need to type memory addresses. Click Import JSON; the app will auto-locate the live FH6 layer table if needed.

7. If import fails with OpenProcess or permission errors, close the app and run it as administrator. If the game was restarted, entered another menu, or reloaded the template, run Auto-locate FH6 again or import again with the correct layer count.

Notes

- The old FH5 signature chain is kept for compatibility, but FH6/Steam builds should use runtime auto-location.
- Current FH6 addresses are valid only for the current game process and editor state.
- If the app cannot find a safe template, confirm the editor is open, the template is ungrouped, and the layer count is exact.
""",
    },
    "zh": {
        "title": app_title(),
        "subtitle": "生成 geometry JSON，并导入到 Forza Horizon 的 Vinyl Group 编辑器。",
        "language": "语言",
        "process": "游戏进程",
        "refresh": "刷新",
        "generate_tab": "生成 JSON",
        "import_tab": "导入",
        "tools_tab": "FH6 工具",
        "tutorial_tab": "教程",
        "images": "图片",
        "add_images": "添加图片",
        "quality": "品质配置",
        "custom_settings": "使用自定义参数",
        "custom_layers": "输出层数",
        "custom_resolution": "最大分辨率",
        "custom_random": "随机样本",
        "custom_mutated": "变异样本",
        "custom_save_at": "保存节点",
        "custom_panel_title": "自定义参数",
        "custom_panel_hint": "上方预设会自动填入这些参数；勾选使用自定义参数后可直接修改。",
        "generate_step_image": "第 1 步 - 选择图片",
        "generate_step_image_hint": "添加 PNG/JPG/BMP 图片。生成的 JSON 会保存在原图片旁边。",
        "generate_step_quality": "第 2 步 - 选择品质",
        "generate_step_quality_hint": "快速配置耗时短；慢速配置会占用更多 GPU 时间，通常画面更干净。",
        "generate_step_run": "第 3 步 - 开始生成",
        "generate_step_run_hint": "点击一次后等待。进度会显示在日志里，生成的 JSON 会自动加入导入页面。",
        "scroll_hint": "添加图片、选择预设；需要时直接修改下方自定义参数。",
        "start_generate": "按当前配置生成",
        "stop_generate": "中断当前生成",
        "open_output": "打开输出目录",
        "preview": "预览",
        "preview_hint": "选择图片或 JSON 后会在这里预览。",
        "preview_unavailable": "当前环境无法显示预览。可安装可选预览依赖，也可以直接继续生成或导入。",
        "logs": "日志",
        "export_logs": "导出详细日志",
        "progress": "进度",
        "json_files": "Geometry JSON 文件",
        "add_json": "添加 JSON",
        "use_outputs": "使用已生成 JSON",
        "step_game": "第 1 步 - 游戏",
        "step_game_hint": "启动 FH6，进入 Vinyl Group Editor，载入未分组的球形模板，然后刷新进程列表。",
        "step_template": "第 2 步 - 模板",
        "step_template_hint": "填写游戏里当前模板显示的真实层数。",
        "step_json": "第 3 步 - JSON",
        "step_json_hint": "使用本软件生成的 JSON，或手动添加 geometry JSON。",
        "step_import": "第 4 步 - 导入",
        "step_import_hint": "只点一次导入。软件会安全定位 FH6 图层表，然后写入图案。",
        "advanced_options": "高级选项",
        "show_advanced": "显示高级",
        "hide_advanced": "隐藏高级",
        "import_preview": "已选 JSON 预览",
        "game_profile": "游戏 profile",
        "pid": "PID",
        "layer_count": "模板层数",
        "easy_import": "简化导入",
        "easy_import_hint": "FH6 通常不需要手填地址。留空即可复用当前 session，或在导入前自动定位。",
        "manual_count": "层数地址",
        "manual_table": "图层表地址",
        "auto_locate": "自动定位 FH6",
        "import_json": "导入 JSON",
        "diagnose": "诊断",
        "save_snapshot": "保存层数快照",
        "compare_snapshot": "对比快照",
        "snapshot_count": "快照层数",
        "current_count": "当前层数",
        "inspect_table": "精查 table",
        "table_address": "候选 table",
        "admin_note": "导入需要管理员权限。如果日志出现 OpenProcess 失败，请用管理员身份启动本程序。",
        "no_game": "未检测到支持的游戏进程",
        "ready": "就绪",
        "running": "运行中",
        "done": "完成",
        "failed": "失败",
        "stopped": "已中断",
        "no_generation_running": "当前没有正在生成的任务。",
        "stopping_generation": "正在中断当前生成...",
        "generation_stopped": "生成已中断。",
        "locating": "正在查找当前 FH6 模板...",
        "located": "已安全定位并验证 FH6 模板。",
        "importing": "正在导入 JSON 到 FH6...",
        "json_too_small": "当前 JSON 可绘制层数远少于模板可用容量，导入会很糊；请换用更高层数的 JSON。",
        "json_needs_more_template_layers": "FH 需要预留 4 个边界层，才能正常保存封面和贴到车上。模板层数建议至少为 JSON 可绘制层数 + 4。",
        "safe_stop": "未找到安全 FH6 模板，已在写入前停止。",
        "tutorial": """小白流程

1. 尽量安装 64 位 Python 3.12，然后运行 install_dependencies.bat。
   NumPy/OpenCV 预览是可选功能；生成和导入不依赖它。
   JSON 生成使用自带的 GPU/OpenCL 生成器，请保持显卡驱动正常。

2. 启动 Forza Horizon 6，进入 Create Vinyl Group / Vinyl Group Editor。

3. 载入或新建一个由大量 sphere 图层组成的模板。建议 500 层以上。导入前必须先 ungroup。

4. 在本软件的“生成 JSON”页添加 PNG/JPG/BMP 图片，选择品质配置，点击“开始生成”。如果预览依赖可用，预览区会先显示原图，JSON 出现后显示生成后的几何预览。

5. 打开“导入”页，添加生成的 JSON，或点击“使用已生成 JSON”。游戏 profile 保持 Forza Horizon 6。

6. 填写游戏里当前模板的真实层数。FH6 通常不需要手动填写内存地址。点击“导入 JSON”，软件会在需要时自动定位当前 FH6 图层表。

7. 如果日志提示 OpenProcess 或权限失败，请关闭软件，用管理员身份重新运行。如果重启过游戏、切换过菜单或重新加载模板，需要用正确层数重新自动定位或重新导入。

说明

- 旧 FH5 签名链仍保留用于兼容；FH6/Steam 构建优先使用运行时自动定位。
- FH6 地址只对当前游戏进程和当前编辑器状态有效。
- 如果软件找不到安全模板，请确认编辑器仍然打开、模板已经 ungroup、层数填写完全正确。
""",
    },
    "ko": {
        "title": app_title(),
        "subtitle": "geometry JSON을 생성하고 Forza Horizon 비닐 그룹 편집기로 가져옵니다.",
        "language": "언어",
        "process": "게임 프로세스",
        "refresh": "새로고침",
        "generate_tab": "JSON 생성",
        "import_tab": "가져오기",
        "tools_tab": "FH6 도구",
        "tutorial_tab": "튜토리얼",
        "images": "이미지",
        "add_images": "이미지 추가",
        "quality": "품질 프로필",
        "custom_settings": "사용자 설정 사용",
        "custom_layers": "출력 레이어",
        "custom_resolution": "최대 해상도",
        "custom_random": "무작위 샘플",
        "custom_mutated": "변형 샘플",
        "custom_save_at": "체크포인트 저장",
        "custom_panel_title": "사용자 설정",
        "custom_panel_hint": "선택한 프리셋 값이 자동으로 채워집니다. 생성 전에 값을 바꾸려면 사용자 설정을 켜세요.",
        "generate_step_image": "1단계 - 이미지 선택",
        "generate_step_image_hint": "PNG/JPG/BMP 이미지를 추가하세요. 생성된 JSON은 원본 이미지 옆에 저장됩니다.",
        "generate_step_quality": "2단계 - 품질 선택",
        "generate_step_quality_hint": "빠른 프로필은 시간이 적게 걸립니다. 느린 프로필은 GPU 시간을 더 쓰지만 보통 더 깔끔합니다.",
        "generate_step_run": "3단계 - 생성",
        "generate_step_run_hint": "한 번 클릭한 뒤 기다리세요. 진행 상황은 로그에 표시되고, 생성된 JSON은 가져오기 페이지에 자동으로 추가됩니다.",
        "scroll_hint": "이미지를 추가하고 프리셋을 선택한 뒤, 필요하면 사용자 설정을 조정하세요.",
        "start_generate": "현재 설정으로 생성",
        "stop_generate": "현재 생성 중지",
        "open_output": "출력 폴더 열기",
        "preview": "미리보기",
        "preview_hint": "이미지나 JSON을 선택하면 여기에 미리보기가 표시됩니다.",
        "preview_unavailable": "미리보기를 사용할 수 없습니다. 선택 미리보기 의존성을 설치하거나, 미리보기 없이 계속 진행하세요.",
        "logs": "로그",
        "export_logs": "자세한 로그 내보내기",
        "progress": "진행 상황",
        "json_files": "Geometry JSON 파일",
        "add_json": "JSON 추가",
        "use_outputs": "생성된 JSON 사용",
        "step_game": "1단계 - 게임",
        "step_game_hint": "FH6를 실행하고 비닐 그룹 편집기를 연 뒤, 그룹 해제된 구체 템플릿을 불러오고 프로세스 목록을 새로고침하세요.",
        "step_template": "2단계 - 템플릿",
        "step_template_hint": "현재 게임 안 템플릿에 표시된 정확한 레이어 수를 입력하세요.",
        "step_json": "3단계 - JSON",
        "step_json_hint": "이 앱에서 생성한 JSON을 사용하거나 geometry JSON을 직접 추가하세요.",
        "step_import": "4단계 - 가져오기",
        "step_import_hint": "가져오기를 한 번만 클릭하세요. 앱이 FH6 레이어 테이블을 안전하게 찾은 뒤 디자인을 씁니다.",
        "advanced_options": "고급 옵션",
        "show_advanced": "고급 옵션 표시",
        "hide_advanced": "고급 옵션 숨기기",
        "import_preview": "선택한 JSON 미리보기",
        "game_profile": "게임 프로필",
        "pid": "PID",
        "layer_count": "템플릿 레이어 수",
        "easy_import": "간편 가져오기",
        "easy_import_hint": "FH6에서는 주소를 비워두세요. 앱이 현재 세션을 재사용하거나 가져오기 전에 자동으로 찾습니다.",
        "manual_count": "레이어 수 주소",
        "manual_table": "레이어 테이블 주소",
        "auto_locate": "FH6 자동 찾기",
        "import_json": "JSON 가져오기",
        "diagnose": "진단",
        "save_snapshot": "레이어 수 스냅샷 저장",
        "compare_snapshot": "스냅샷 비교",
        "snapshot_count": "스냅샷 레이어 수",
        "current_count": "현재 레이어 수",
        "inspect_table": "테이블 검사",
        "table_address": "후보 테이블",
        "admin_note": "가져오기는 관리자 권한이 필요합니다. OpenProcess 실패가 보이면 이 앱을 관리자 권한으로 실행하세요.",
        "no_game": "지원되는 게임 프로세스를 찾지 못했습니다",
        "ready": "준비됨",
        "running": "실행 중",
        "done": "완료",
        "failed": "실패",
        "stopped": "중지됨",
        "no_generation_running": "현재 실행 중인 생성 작업이 없습니다.",
        "stopping_generation": "현재 생성을 중지하는 중...",
        "generation_stopped": "생성이 중지되었습니다.",
        "locating": "현재 FH6 템플릿을 찾는 중...",
        "located": "FH6 템플릿을 찾고 검증했습니다.",
        "importing": "JSON을 FH6로 가져오는 중...",
        "json_too_small": "선택한 JSON의 그릴 수 있는 레이어 수가 템플릿 사용 가능 용량보다 훨씬 적습니다. 가져오면 흐릿해 보이므로 더 높은 레이어 JSON을 선택하세요.",
        "json_needs_more_template_layers": "FH는 커버 저장과 적용 범위를 올바르게 처리하려면 경계 레이어 4개가 필요합니다. JSON의 그릴 수 있는 레이어 수 + 4 이상인 템플릿을 사용하세요.",
        "safe_stop": "안전한 FH6 템플릿을 찾지 못해 쓰기 전에 중지했습니다.",
        "tutorial": """초보자용 작업 순서

1. 가능하면 64비트 Python 3.12를 설치한 뒤 install_dependencies.bat을 실행하세요.
   NumPy/OpenCV 미리보기는 선택 기능입니다. 생성과 가져오기는 이 의존성 없이도 동작합니다.
   JSON 생성은 포함된 GPU/OpenCL 생성기를 사용하므로 그래픽 드라이버를 최신 상태로 유지하세요.

2. Forza Horizon 6를 실행하고 Create Vinyl Group / Vinyl Group Editor로 들어갑니다.

3. 많은 단순 sphere 레이어로 만든 템플릿을 불러오거나 새로 만드세요. 500개 이상의 레이어를 권장합니다. 가져오기 전에는 반드시 템플릿을 ungroup해야 합니다.

4. 이 앱의 JSON 생성 페이지에서 PNG/JPG/BMP 이미지를 추가하고 품질 프로필을 선택한 뒤 생성 시작을 클릭하세요. 미리보기 의존성이 있으면 미리보기 영역에 원본 이미지가 먼저 표시되고, JSON이 만들어지면 생성된 geometry 미리보기가 표시됩니다.

5. 가져오기 페이지를 여세요. 생성된 JSON을 추가하거나 생성된 JSON 사용을 클릭하세요. 게임 프로필은 Forza Horizon 6로 둡니다.

6. 현재 게임에 불러온 템플릿의 실제 레이어 수를 입력하세요. FH6에서는 보통 메모리 주소를 직접 입력할 필요가 없습니다. JSON 가져오기를 클릭하면 필요할 때 앱이 현재 FH6 레이어 테이블을 자동으로 찾습니다.

7. OpenProcess 또는 권한 오류가 보이면 앱을 닫고 관리자 권한으로 다시 실행하세요. 게임을 다시 시작했거나, 다른 메뉴로 이동했거나, 템플릿을 다시 불러왔다면 정확한 레이어 수로 다시 자동 찾기 또는 가져오기를 실행하세요.

참고

- 기존 FH5 시그니처 체인은 호환성을 위해 유지됩니다. FH6/Steam 빌드는 런타임 자동 찾기를 우선 사용해야 합니다.
- 현재 FH6 주소는 현재 게임 프로세스와 현재 편집기 상태에서만 유효합니다.
- 앱이 안전한 템플릿을 찾지 못하면 편집기가 열려 있는지, 템플릿이 ungroup 상태인지, 레이어 수가 정확한지 확인하세요.
""",
    },
}


def ensure_dirs():
    PROBE_DIR.mkdir(parents=True, exist_ok=True)


def tr(lang, key):
    return TEXT[lang].get(key, TEXT["en"].get(key, key))


def game_processes():
    names = {name.lower(): key for key, profile in PROFILES.items() for name in profile.process_names}
    found = []
    for proc in psutil.process_iter(["pid", "name", "exe"]):
        try:
            name = proc.info.get("name") or ""
            key = names.get(name.lower())
            if key:
                found.append({
                    "pid": proc.info["pid"],
                    "name": name,
                    "profile": key,
                    "label": f"{name} pid {proc.info['pid']}",
                })
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue
    return found


def parse_hex_or_empty(value):
    value = str(value or "").strip()
    return value or None


def load_session_location():
    if not SESSION_PATH.exists():
        return None
    try:
        return json.loads(SESSION_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def clear_session_location():
    try:
        SESSION_PATH.unlink(missing_ok=True)
    except OSError:
        pass


def session_pid_is_live(session, game):
    try:
        pid = int(session.get("pid", -1))
        proc = psutil.Process(pid)
        profile = PROFILES.get(game)
        return bool(profile and proc.name().lower() in [name.lower() for name in profile.process_names])
    except (psutil.Error, TypeError, ValueError):
        return False


def session_matches_current_import(session, game, pid, layer_count):
    if not session:
        return False
    if str(session.get("layer_count", "")) != str(layer_count):
        return False
    if not session_pid_is_live(session, game):
        return False
    try:
        session_pid = int(session.get("pid", -1))
        return not pid or int(pid) == session_pid
    except (TypeError, ValueError):
        return False


def load_cv2():
    global _CV2_CACHE, _CV2_ERROR
    if _CV2_CACHE is not None:
        return _CV2_CACHE
    if _CV2_ERROR is not None:
        return None
    try:
        import cv2
        import numpy as np
        _CV2_CACHE = (cv2, np)
        return _CV2_CACHE
    except BaseException as exc:
        _CV2_ERROR = exc
        return None


def resize_keep_aspect(image, max_size=PREVIEW_MAX):
    loaded = load_cv2()
    if not loaded:
        return image
    cv2, _np = loaded
    height, width = image.shape[:2]
    scale = min(max_size / max(width, height), 1.0)
    if scale < 1.0:
        image = cv2.resize(image, (int(width * scale), int(height * scale)), interpolation=cv2.INTER_AREA)
    return image


def image_to_photo(image):
    loaded = load_cv2()
    if not loaded:
        return None
    cv2, _np = loaded
    image = resize_keep_aspect(image)
    ok, encoded = cv2.imencode(".png", image)
    if not ok:
        return None
    return encoded.tobytes()


def render_source_image(path):
    loaded = load_cv2()
    if not loaded:
        return None
    cv2, _np = loaded
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        return None
    return image_to_photo(image)


def render_geometry_json(path):
    loaded = load_cv2()
    if not loaded:
        return None
    cv2, np = loaded
    try:
        data = load_normalized_geometry(path)
        shapes = data["shapes"]
        image_w, image_h = [int(v) for v in shapes[0]["data"][2:]]
        bg_r, bg_g, bg_b, bg_a = [int(v) for v in shapes[0]["color"]]
        preview = np.zeros((image_h, image_w, 3), np.uint8)
        if bg_a > 0:
            preview[:, :] = (bg_b, bg_g, bg_r)
        else:
            preview[:, :] = (38, 38, 38)
            tile = 32
            for y in range(0, image_h, tile):
                for x in range(0, image_w, tile):
                    if ((x // tile) + (y // tile)) % 2 == 0:
                        preview[y:y + tile, x:x + tile] = (58, 58, 58)
        for shape in shapes[1:]:
            color = [int(v) for v in shape.get("color", [])]
            if len(color) == 4 and color[3] <= 0:
                continue
            r, g, b, _a = color
            shape_type = int(shape.get("type", 0))
            if shape_type == ROTATED_ELLIPSE:
                x, y, w, h, rot_deg = shape["data"]
                center = (int(round(x)), int(round(y)))
                axes = (max(1, int(round(h))), max(1, int(round(w))))
                preview = cv2.ellipse(preview, center, axes, -90 + float(rot_deg), 0.0, 360.0, (b, g, r), thickness=-1)
            elif shape_type == RECTANGLE:
                x, y, w, h = shape["data"]
                x0 = int(round(x - w / 2))
                y0 = int(round(y - h / 2))
                x1 = int(round(x + w / 2))
                y1 = int(round(y + h / 2))
                preview = cv2.rectangle(preview, (x0, y0), (x1, y1), (b, g, r), thickness=-1)
        return image_to_photo(preview)
    except Exception:
        return None


class App:
    def __init__(self, initial_images):
        ensure_dirs()
        self.root = Tk()
        self.root.title(app_title())
        self.root.geometry("1180x780")
        self.lang = "en"
        self.queue = queue.Queue()
        self.shutdown_event = threading.Event()
        self.active_processes = set()
        self.process_lock = threading.Lock()
        self.generation_lock = threading.Lock()
        self.generation_running = False
        self.current_generator_proc = None
        self.eta_intervals = deque(maxlen=24)
        self.eta_last_layer = None
        self.eta_last_time = None
        self.eta_smoothed_seconds_per_layer = None
        self.eta_display_remaining = None
        self.closed = False
        self.settings = load_settings()
        self.images = [Path(path) for path in initial_images if Path(path).exists()]
        self.json_files = []
        self.outputs = []
        self.processes = []
        self.photo = None
        self.use_custom_settings = StringVar(value="0")
        self.custom_stop_at = StringVar()
        self.custom_max_resolution = StringVar()
        self.custom_random_samples = StringVar()
        self.custom_mutated_samples = StringVar()
        self.custom_save_at = StringVar()
        self.translated = []
        self.detailed_log_lock = threading.Lock()
        self.detailed_log_lines = deque()
        self.detailed_log_chars = 0
        self.status = StringVar(value=tr(self.lang, "ready"))
        self.progress_text = StringVar(value="")
        self.selected_profile = StringVar()
        self.selected_game = StringVar(value="fh6")
        self.selected_pid = StringVar()
        self.layer_count = StringVar()
        self.snapshot_count = StringVar()
        self.current_count = StringVar()
        self.count_address = StringVar()
        self.table_address = StringVar()
        self.inspect_table_value = StringVar()
        self.advanced_visible = False
        self._build()
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)
        self.refresh_processes()
        if self.settings:
            self.selected_profile.set(self.settings[min(2, len(self.settings) - 1)]["label"])
            self._update_setting_description()
        self._render_lists()
        self._poll_queue()

    def _configure_styles(self):
        style = ttk.Style(self.root)
        style.configure(
            "Primary.TNotebook.Tab",
            padding=(18, 8),
            font=("Segoe UI", 10, "bold"),
        )
        style.map(
            "Primary.TNotebook.Tab",
            background=[("selected", "#d8e8ff"), ("active", "#eef5ff")],
            foreground=[("selected", "#003b73"), ("active", "#003b73")],
        )

    def _register_process(self, proc):
        with self.process_lock:
            self.active_processes.add(proc)

    def _popen_registered(self, cmd, **kwargs):
        # Hold process_lock across Popen + registration so on_close cannot miss
        # a child process that starts while the window is closing.
        with self.process_lock:
            if self.shutdown_event.is_set() or self.closed:
                return None
            proc = subprocess.Popen(cmd, **kwargs)
            self.active_processes.add(proc)
            return proc

    def _unregister_process(self, proc):
        with self.process_lock:
            self.active_processes.discard(proc)

    def _terminate_process(self, proc):
        if proc.poll() is not None:
            return
        try:
            if os.name == "nt":
                subprocess.run(
                    ["taskkill", "/PID", str(proc.pid), "/T", "/F"],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    creationflags=subprocess.CREATE_NO_WINDOW,
                    timeout=5,
                )
            else:
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
        except Exception:
            try:
                proc.kill()
            except Exception:
                pass

    def _terminate_active_processes(self):
        with self.process_lock:
            processes = list(self.active_processes)
        for proc in processes:
            self._terminate_process(proc)

    def on_close(self):
        self.closed = True
        self.shutdown_event.set()
        self._terminate_active_processes()
        self.root.destroy()

    def _label(self, parent, key, **kwargs):
        widget = Label(parent, text=tr(self.lang, key), **kwargs)
        self.translated.append((widget, key, "text"))
        return widget

    def _button(self, parent, key, command, **kwargs):
        widget = Button(parent, text=tr(self.lang, key), command=command, **kwargs)
        self.translated.append((widget, key, "text"))
        return widget

    def _build(self):
        self._configure_styles()
        header = Frame(self.root)
        header.pack(fill=X, padx=14, pady=(12, 6))
        title_box = Frame(header)
        title_box.pack(side=LEFT, fill=X, expand=True)
        self._label(title_box, "title", font=("Segoe UI", 18, "bold"), anchor="w").pack(fill=X)
        self._label(title_box, "subtitle", anchor="w", fg="#555").pack(fill=X)
        right = Frame(header)
        right.pack(side=RIGHT)
        self._label(right, "language").pack(anchor="e")
        self.lang_combo = ttk.Combobox(right, values=list(LANGUAGES.keys()), state="readonly", width=10)
        self.lang_combo.set("English")
        self.lang_combo.pack(anchor="e")
        self.lang_combo.bind("<<ComboboxSelected>>", self._on_language)

        process_bar = Frame(self.root)
        process_bar.pack(fill=X, padx=14, pady=(0, 8))
        self._label(process_bar, "process").pack(side=LEFT)
        self.process_combo = ttk.Combobox(process_bar, textvariable=self.selected_pid, state="readonly", width=44)
        self.process_combo.pack(side=LEFT, padx=8)
        self._button(process_bar, "refresh", self.refresh_processes).pack(side=LEFT)
        Label(process_bar, textvariable=self.status, anchor="e").pack(side=RIGHT)

        self.tabs = ttk.Notebook(self.root, style="Primary.TNotebook")
        self.tabs.pack(fill=BOTH, expand=True, padx=14, pady=(0, 8))
        self.generate_tab = Frame(self.tabs)
        self.import_tab = Frame(self.tabs)
        self.tools_tab = Frame(self.tabs)
        self.tutorial_tab = Frame(self.tabs)
        self.tabs.add(self.generate_tab, text=tr(self.lang, "generate_tab"))
        self.tabs.add(self.import_tab, text=tr(self.lang, "import_tab"))
        self.tabs.add(self.tutorial_tab, text=tr(self.lang, "tutorial_tab"))

        self._build_generate_tab()
        self._build_import_tab()
        self._build_tools_tab()
        self._build_tutorial_tab()
        self._build_log()

    def _build_generate_tab(self):
        left_outer = Frame(self.generate_tab)
        left_outer.pack(side=LEFT, fill=BOTH, expand=True, padx=(0, 10), pady=10)
        right = Frame(self.generate_tab)
        right.pack(side=RIGHT, fill=BOTH, expand=True, pady=10)

        self._label(left_outer, "scroll_hint", anchor="w", justify=LEFT, fg="#8a5300").pack(fill=X, pady=(0, 6))
        scroll_area = Frame(left_outer)
        scroll_area.pack(fill=BOTH, expand=True, pady=(0, 8))
        left_canvas = Canvas(scroll_area, highlightthickness=0)
        left_scroll = ttk.Scrollbar(scroll_area, orient="vertical", command=left_canvas.yview)
        left_canvas.configure(yscrollcommand=left_scroll.set)
        left_canvas.pack(side=LEFT, fill=BOTH, expand=True)
        left_scroll.pack(side=RIGHT, fill="y")
        left = Frame(left_canvas)
        left_window = left_canvas.create_window((0, 0), window=left, anchor="nw")

        def _update_scroll_region(_event=None):
            left_canvas.configure(scrollregion=left_canvas.bbox("all"))

        def _match_canvas_width(event):
            left_canvas.itemconfigure(left_window, width=event.width)

        def _mousewheel(event):
            left_canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

        def _bind_mousewheel(_event=None):
            left_canvas.bind_all("<MouseWheel>", _mousewheel)

        def _unbind_mousewheel(_event=None):
            left_canvas.unbind_all("<MouseWheel>")

        left.bind("<Configure>", _update_scroll_region)
        left_canvas.bind("<Configure>", _match_canvas_width)
        scroll_area.bind("<Enter>", _bind_mousewheel)
        scroll_area.bind("<Leave>", _unbind_mousewheel)

        step1 = ttk.LabelFrame(left, text=tr(self.lang, "generate_step_image"))
        self.translated.append((step1, "generate_step_image", "text"))
        step1.pack(fill=X, pady=(0, 6))
        row = Frame(step1)
        row.pack(fill=X, padx=10, pady=(6, 2))
        self._label(row, "images").pack(side=LEFT)
        self._button(row, "add_images", self.add_images).pack(side=RIGHT)
        self.image_list = Listbox(step1, height=3)
        self.image_list.pack(fill=X, padx=10, pady=(2, 8))
        self.image_list.bind("<<ListboxSelect>>", self._preview_selected_image)

        step2 = ttk.LabelFrame(left, text=tr(self.lang, "generate_step_quality"))
        self.translated.append((step2, "generate_step_quality", "text"))
        step2.pack(fill=X, pady=(0, 6))
        profile_row = Frame(step2)
        profile_row.pack(fill=X, padx=10, pady=(8, 4))
        self._label(profile_row, "quality").pack(side=LEFT)
        self.profile_combo = ttk.Combobox(
            profile_row,
            values=[item["label"] for item in self.settings],
            textvariable=self.selected_profile,
            state="readonly",
            width=32,
        )
        self.profile_combo.pack(side=LEFT, fill=X, expand=True, padx=(8, 0))
        self.profile_combo.bind("<<ComboboxSelected>>", self._update_setting_description)
        self.setting_description = Label(step2, text="", anchor="w", justify=LEFT, wraplength=500)
        self.setting_description.pack(fill=X, padx=10, pady=(0, 8))

        custom_section = ttk.LabelFrame(left, text=tr(self.lang, "custom_panel_title"))
        self.translated.append((custom_section, "custom_panel_title", "text"))
        custom_section.pack(fill=X, pady=(0, 6))
        self._label(custom_section, "custom_panel_hint", anchor="w", justify=LEFT, wraplength=540, fg="#005a9e").pack(fill=X, padx=10, pady=(6, 2))
        custom_toggle = Checkbutton(
            custom_section,
            text=tr(self.lang, "custom_settings"),
            variable=self.use_custom_settings,
            onvalue="1",
            offvalue="0",
            command=self._sync_custom_state,
        )
        custom_toggle.pack(anchor="w", padx=10, pady=(0, 2))
        self.translated.append((custom_toggle, "custom_settings", "text"))
        custom_grid = Frame(custom_section)
        custom_grid.pack(fill=X, padx=10, pady=(0, 6))
        self.custom_fields = []
        custom_specs = [
            ("custom_layers", self.custom_stop_at),
            ("custom_resolution", self.custom_max_resolution),
            ("custom_random", self.custom_random_samples),
            ("custom_mutated", self.custom_mutated_samples),
            ("custom_save_at", self.custom_save_at),
        ]
        for row_index, (key, variable) in enumerate(custom_specs):
            label = self._label(custom_grid, key, anchor="w")
            label.grid(row=row_index, column=0, sticky="w", pady=1, padx=(0, 8))
            entry = Entry(custom_grid, textvariable=variable, width=18)
            entry.grid(row=row_index, column=1, sticky="ew", pady=1)
            self.custom_fields.append(entry)
        custom_grid.columnconfigure(1, weight=1)
        self._sync_custom_state()

        step3 = ttk.LabelFrame(left_outer, text=tr(self.lang, "generate_step_run"))
        self.translated.append((step3, "generate_step_run", "text"))
        step3.pack(fill=X)
        self._label(step3, "generate_step_run_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        actions = Frame(step3)
        actions.pack(fill=X, padx=10, pady=(4, 12))
        self.generate_button = self._button(actions, "start_generate", self.start_generate, font=("Segoe UI", 12, "bold"), height=2)
        self.generate_button.pack(side=LEFT, fill=X, expand=True)
        self.stop_generate_button = self._button(actions, "stop_generate", self.stop_generate, height=2, state="disabled")
        self.stop_generate_button.pack(side=LEFT, padx=8)
        self._button(actions, "open_output", self.open_output_folder, height=2).pack(side=LEFT)

        self._label(right, "preview", anchor="w", font=("Segoe UI", 12, "bold")).pack(fill=X)
        self.preview_label = Label(right, text=tr(self.lang, "preview_hint"), bg="#202020", fg="#dddddd", width=60, height=24)
        self.preview_label.pack(fill=BOTH, expand=True, pady=6)

    def _build_import_tab(self):
        left = Frame(self.import_tab)
        left.pack(side=LEFT, fill=BOTH, expand=True, padx=(0, 10), pady=10)
        right = Frame(self.import_tab)
        right.pack(side=RIGHT, fill=BOTH, expand=True, pady=10)

        step1 = ttk.LabelFrame(left, text=tr(self.lang, "step_game"))
        self.translated.append((step1, "step_game", "text"))
        step1.pack(fill=X, pady=(0, 10))
        self._label(step1, "step_game_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        game_row = Frame(step1)
        game_row.pack(fill=X, padx=10, pady=(0, 10))
        self._label(game_row, "game_profile").pack(side=LEFT)
        self.import_game_combo = ttk.Combobox(game_row, values=list(PROFILES.keys()), textvariable=self.selected_game, state="readonly", width=8)
        self.import_game_combo.pack(side=LEFT, padx=8)
        self._label(game_row, "pid").pack(side=LEFT)
        self.import_pid_entry = Entry(game_row, textvariable=self.selected_pid, width=30)
        self.import_pid_entry.pack(side=LEFT, padx=8)
        self._button(game_row, "refresh", self.refresh_processes).pack(side=LEFT)

        step2 = ttk.LabelFrame(left, text=tr(self.lang, "step_template"))
        self.translated.append((step2, "step_template", "text"))
        step2.pack(fill=X, pady=(0, 10))
        self._label(step2, "step_template_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        template_row = Frame(step2)
        template_row.pack(fill=X, padx=10, pady=(0, 10))
        self._label(template_row, "layer_count").pack(side=LEFT)
        Entry(template_row, textvariable=self.layer_count, width=18, font=("Segoe UI", 13)).pack(side=LEFT, padx=8)

        step3 = ttk.LabelFrame(left, text=tr(self.lang, "step_json"))
        self.translated.append((step3, "step_json", "text"))
        step3.pack(fill=BOTH, expand=True, pady=(0, 10))
        self._label(step3, "step_json_hint", anchor="w", justify=LEFT, wraplength=540).pack(fill=X, padx=10, pady=(8, 4))
        row = Frame(step3)
        row.pack(fill=X, padx=10)
        self._label(row, "json_files").pack(side=LEFT)
        self._button(row, "add_json", self.add_json).pack(side=RIGHT)
        self._button(row, "use_outputs", self.use_generated_outputs).pack(side=RIGHT, padx=8)
        self.json_list = Listbox(step3, height=10)
        self.json_list.pack(fill=BOTH, expand=True, padx=10, pady=6)
        self.json_list.bind("<<ListboxSelect>>", self._preview_selected_json)

        step4 = ttk.LabelFrame(right, text=tr(self.lang, "step_import"))
        self.translated.append((step4, "step_import", "text"))
        step4.pack(fill=X, pady=(0, 10))
        self._label(step4, "step_import_hint", anchor="w", justify=LEFT, wraplength=500).pack(fill=X, padx=10, pady=(8, 4))
        self._label(step4, "easy_import_hint", anchor="w", justify=LEFT, wraplength=500, fg="#555").pack(fill=X, padx=10, pady=4)
        self._label(step4, "admin_note", anchor="w", justify=LEFT, wraplength=500, fg="#8a5300").pack(fill=X, padx=10, pady=4)
        actions = Frame(step4)
        actions.pack(fill=X, padx=10, pady=12)
        self._button(actions, "import_json", self.start_import, font=("Segoe UI", 13, "bold"), height=2).pack(side=LEFT, fill=X, expand=True)
        self.advanced_button = self._button(actions, "show_advanced", self.toggle_advanced)
        self.advanced_button.pack(side=LEFT, padx=(8, 0))

        self.advanced_frame = ttk.LabelFrame(right, text=tr(self.lang, "advanced_options"))
        self.translated.append((self.advanced_frame, "advanced_options", "text"))
        self._field(self.advanced_frame, "manual_count", self.count_address, row=0)
        self._field(self.advanced_frame, "manual_table", self.table_address, row=1)
        self._button(self.advanced_frame, "auto_locate", self.start_auto_locate).grid(row=2, column=0, columnspan=2, sticky="ew", pady=(8, 4))

        self._label(right, "import_preview", anchor="w", font=("Segoe UI", 12, "bold")).pack(fill=X, pady=(8, 0))
        self.import_preview_label = Label(right, text=tr(self.lang, "preview_hint"), bg="#202020", fg="#dddddd", width=56, height=20)
        self.import_preview_label.pack(fill=BOTH, expand=True, pady=6)

    def _build_tools_tab(self):
        form = Frame(self.tools_tab)
        form.pack(fill=X, padx=10, pady=10)
        self._field(form, "layer_count", self.layer_count, row=0)
        self._field(form, "snapshot_count", self.snapshot_count, row=1)
        self._field(form, "current_count", self.current_count, row=2)
        self._field(form, "table_address", self.inspect_table_value, row=3)
        actions = Frame(self.tools_tab)
        actions.pack(fill=X, padx=10, pady=8)
        self._button(actions, "diagnose", self.start_diagnose).pack(side=LEFT)
        self._button(actions, "auto_locate", self.start_auto_locate).pack(side=LEFT, padx=6)
        self._button(actions, "save_snapshot", self.start_save_snapshot).pack(side=LEFT, padx=6)
        self._button(actions, "compare_snapshot", self.start_compare_snapshot).pack(side=LEFT, padx=6)
        self._button(actions, "inspect_table", self.start_inspect_table).pack(side=LEFT, padx=6)

    def _build_tutorial_tab(self):
        self.tutorial_text = Text(self.tutorial_tab, wrap="word")
        self.tutorial_text.pack(fill=BOTH, expand=True, padx=10, pady=10)
        self._update_tutorial()

    def _build_log(self):
        row = Frame(self.root)
        row.pack(fill=X, padx=14)
        self._label(row, "logs", anchor="w").pack(side=LEFT)
        self._button(row, "export_logs", self.export_detailed_log).pack(side=RIGHT)
        self._label(row, "progress", anchor="e").pack(side=LEFT, padx=(18, 4))
        Label(row, textvariable=self.progress_text, anchor="w", fg="#005a9e").pack(side=LEFT, fill=X, expand=True)
        self.log = Text(self.root, height=9)
        self.log.pack(fill=BOTH, padx=14, pady=(0, 12))

    def _field(self, parent, key, variable, row, values=None, readonly=False):
        self._label(parent, key, anchor="w").grid(row=row, column=0, sticky="w", padx=(0, 8), pady=5)
        if values:
            widget = ttk.Combobox(parent, values=values, textvariable=variable, state="readonly" if readonly else "normal")
        else:
            widget = Entry(parent, textvariable=variable)
        widget.grid(row=row, column=1, sticky="ew", pady=5)
        parent.columnconfigure(1, weight=1)
        return widget

    def _on_language(self, _event=None):
        self.lang = LANGUAGES.get(self.lang_combo.get(), "en")
        for widget, key, option in self.translated:
            try:
                widget.config(**{option: tr(self.lang, key)})
            except Exception:
                pass
        self.tabs.tab(self.generate_tab, text=tr(self.lang, "generate_tab"))
        self.tabs.tab(self.import_tab, text=tr(self.lang, "import_tab"))
        self.tabs.tab(self.tutorial_tab, text=tr(self.lang, "tutorial_tab"))
        if self.photo is None:
            self.preview_label.config(text=tr(self.lang, "preview_hint"))
            if hasattr(self, "import_preview_label"):
                self.import_preview_label.config(text=tr(self.lang, "preview_hint"))
        if hasattr(self, "advanced_button"):
            self.advanced_button.config(text=tr(self.lang, "hide_advanced" if self.advanced_visible else "show_advanced"))
        self._update_tutorial()
        self.status.set(tr(self.lang, "ready"))

    def _update_tutorial(self):
        self.tutorial_text.config(state="normal")
        self.tutorial_text.delete("1.0", END)
        self.tutorial_text.insert(END, tr(self.lang, "tutorial"))
        self.tutorial_text.config(state="disabled")

    def _update_setting_description(self, _event=None):
        item = self._selected_setting()
        self.setting_description.config(text=item["description"] if item else "No settings profiles found.")
        if item and self.use_custom_settings.get() != "1":
            values = item.get("values", {})
            self.custom_stop_at.set(values.get("stopAt", "3000"))
            self.custom_max_resolution.set(values.get("maxResolution", "1200"))
            self.custom_random_samples.set(values.get("randomSamples", "3000"))
            self.custom_mutated_samples.set(values.get("mutatedSamples", "1000"))
            self.custom_save_at.set(values.get("saveAt", values.get("stopAt", "3000")))

    def _sync_custom_state(self):
        state = "normal" if self.use_custom_settings.get() == "1" else "disabled"
        for entry in getattr(self, "custom_fields", []):
            entry.config(state=state)
        if state == "disabled":
            self._update_setting_description()

    def _effective_setting(self):
        setting = self._selected_setting()
        if not setting or self.use_custom_settings.get() != "1":
            return setting
        custom = {
            "stopAt": self.custom_stop_at.get(),
            "maxResolution": self.custom_max_resolution.get(),
            "randomSamples": self.custom_random_samples.get(),
            "mutatedSamples": self.custom_mutated_samples.get(),
            "saveAt": self.custom_save_at.get(),
        }
        if not custom["saveAt"] and custom["stopAt"]:
            custom["saveAt"] = custom["stopAt"]
        return write_custom_settings(setting, custom)

    def toggle_advanced(self):
        self.advanced_visible = not self.advanced_visible
        if self.advanced_visible:
            self.advanced_frame.pack(fill=X, pady=(0, 10))
        else:
            self.advanced_frame.pack_forget()
        self.advanced_button.config(text=tr(self.lang, "hide_advanced" if self.advanced_visible else "show_advanced"))

    def _selected_setting(self):
        label = self.selected_profile.get()
        for item in self.settings:
            if item["label"] == label:
                return item
        return self.settings[0] if self.settings else None

    def _render_lists(self):
        self.image_list.delete(0, END)
        for path in self.images:
            self.image_list.insert(END, str(path))
        self.json_list.delete(0, END)
        for path in self.json_files:
            self.json_list.insert(END, str(path))

    def log_line(self, message):
        timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
        self._record_detail(f"UI: {message}")
        self.log.insert(END, f"[{timestamp}] {message}\n")
        self.log.see(END)

    def _record_detail(self, message):
        timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
        text = str(message).rstrip()
        entry = f"[{timestamp}] {text}"
        with self.detailed_log_lock:
            self.detailed_log_lines.append(entry)
            self.detailed_log_chars += len(entry) + 1
            while self.detailed_log_chars > DETAILED_LOG_MEMORY_LIMIT and self.detailed_log_lines:
                removed = self.detailed_log_lines.popleft()
                self.detailed_log_chars -= len(removed) + 1

    def _format_command(self, cmd):
        return subprocess.list2cmdline([str(item) for item in cmd])

    def _diagnostic_log_header(self):
        try:
            profile = self._selected_setting()
            profile_name = profile["label"] if profile else ""
            profile_path = str(profile["path"]) if profile else ""
        except Exception:
            profile_name = ""
            profile_path = ""
        selected_pid = self.selected_pid_value()
        generator_exists = GENERATOR_EXE.exists()
        lines = [
            f"{APP_DISPLAY_NAME} detailed log",
            f"Generated at: {datetime.now().isoformat(timespec='seconds')}",
            f"App version: {__version__}",
            f"Python: {sys.version.replace(os.linesep, ' ')}",
            f"Platform: {platform.platform()}",
            f"Root: {ROOT}",
            f"Generator: {GENERATOR_EXE} exists={generator_exists}",
            f"Selected game: {self.selected_game.get()}",
            f"Selected PID: {selected_pid}",
            f"Selected process label: {self.selected_pid.get()}",
            f"Template layer count: {self.layer_count.get()}",
            f"Manual count address: {self.count_address.get()}",
            f"Manual table address: {self.table_address.get()}",
            f"Quality profile: {profile_name}",
            f"Quality profile path: {profile_path}",
            f"Custom settings enabled: {self.use_custom_settings.get()}",
            f"Images: {len(self.images)}",
            *[f"  image: {path}" for path in self.images],
            f"JSON files: {len(self.json_files)}",
            *[f"  json: {path}" for path in self.json_files],
            f"Generated outputs: {len(self.outputs)}",
            *[f"  output: {path}" for path in self.outputs],
        ]
        if SESSION_PATH.exists():
            try:
                session_text = SESSION_PATH.read_text(encoding="utf-8", errors="replace")
            except OSError as exc:
                session_text = f"<failed to read session: {exc}>"
            lines.extend(["Current FH6 session file:", session_text[:4000]])
        return "\n".join(lines).rstrip() + "\n"

    def _build_detailed_log_text(self):
        header = self._diagnostic_log_header()
        try:
            visible_log = self.log.get("1.0", END).strip()
        except Exception:
            visible_log = ""
        with self.detailed_log_lock:
            detail_log = "\n".join(self.detailed_log_lines).strip()
        body = "\n\n".join(
            section
            for section in (
                "=== Detailed Event Log ===\n" + (detail_log or "<empty>"),
                "=== Visible UI Log ===\n" + (visible_log or "<empty>"),
            )
            if section
        )
        marker = f"\n\n--- Log truncated to last {DETAILED_LOG_OUTPUT_LIMIT} characters ---\n"
        prefix = header + "\n"
        budget = DETAILED_LOG_OUTPUT_LIMIT - len(prefix)
        if budget <= len(marker):
            result = (prefix + body)[-DETAILED_LOG_OUTPUT_LIMIT:]
            return result if len(result) <= DETAILED_LOG_OUTPUT_LIMIT else result[-DETAILED_LOG_OUTPUT_LIMIT:]
        if len(body) > budget:
            body = marker + body[-(budget - len(marker)):]
        result = (prefix + body).rstrip()
        if len(result) >= DETAILED_LOG_OUTPUT_LIMIT:
            result = result[:DETAILED_LOG_OUTPUT_LIMIT - 1]
        return result + "\n"

    def export_detailed_log(self):
        initial = f"forza-painter-fh6-log-{datetime.now().strftime('%Y%m%d-%H%M%S')}.txt"
        output = filedialog.asksaveasfilename(
            title="Export detailed log",
            defaultextension=".txt",
            initialfile=initial,
            filetypes=[("Text log", "*.txt"), ("All files", "*.*")],
        )
        if not output:
            return
        text = self._build_detailed_log_text()
        try:
            Path(output).write_text(text, encoding="utf-8")
        except OSError as exc:
            self.log_line(f"Failed to export detailed log: {exc}")
            return
        self.log_line(f"Detailed log exported: {output} ({len(text)} chars, limit {DETAILED_LOG_OUTPUT_LIMIT}).")

    def _reset_generation_eta(self):
        self.eta_intervals.clear()
        self.eta_last_layer = None
        self.eta_last_time = None
        self.eta_smoothed_seconds_per_layer = None
        self.eta_display_remaining = None

    def _format_remaining_time(self, seconds):
        seconds = max(0, int(round(seconds)))
        hours, remainder = divmod(seconds, 3600)
        minutes, seconds = divmod(remainder, 60)
        suffix = {"zh": "剩余", "ko": "남음"}.get(self.lang, "left")
        if hours:
            return f"{hours}h {minutes:02d}m {suffix}"
        if minutes:
            return f"{minutes}m {seconds:02d}s {suffix}"
        return f"{seconds}s {suffix}"

    def _progress_with_eta(self, friendly):
        match = re.match(r"Generated layer\s+(\d+)/(\d+)", friendly)
        if not match:
            return friendly
        current = int(match.group(1))
        total = int(match.group(2))
        now = time.time()
        if self.eta_last_layer is None:
            self.eta_last_layer = current
            self.eta_last_time = now
            return friendly
        layer_delta = current - self.eta_last_layer
        elapsed_seconds = now - self.eta_last_time
        self.eta_last_layer = current
        self.eta_last_time = now
        if layer_delta <= 0:
            return friendly
        if elapsed_seconds >= 0.05:
            self.eta_intervals.append(elapsed_seconds / layer_delta)
        remaining_layers = max(0, total - current)
        if remaining_layers == 0:
            self.eta_display_remaining = 0
            eta_time = datetime.fromtimestamp(now).strftime("%H:%M:%S")
            return f"{friendly} | ETA {eta_time} ({self._format_remaining_time(0)})"
        if not self.eta_intervals:
            return friendly
        intervals = sorted(self.eta_intervals)
        seconds_per_layer = intervals[len(intervals) // 2]
        if self.eta_smoothed_seconds_per_layer is None:
            self.eta_smoothed_seconds_per_layer = seconds_per_layer
        else:
            self.eta_smoothed_seconds_per_layer = (
                self.eta_smoothed_seconds_per_layer * 0.75
                + seconds_per_layer * 0.25
            )
        remaining_seconds = self.eta_smoothed_seconds_per_layer * remaining_layers
        if self.eta_display_remaining is None:
            self.eta_display_remaining = remaining_seconds
        else:
            expected_remaining = max(0, self.eta_display_remaining - elapsed_seconds)
            self.eta_display_remaining = expected_remaining * 0.8 + remaining_seconds * 0.2
        remaining_seconds = self.eta_display_remaining
        eta_time = datetime.fromtimestamp(now + remaining_seconds).strftime("%H:%M:%S")
        return f"{friendly} | ETA {eta_time} ({self._format_remaining_time(remaining_seconds)})"

    def friendly_generator_line(self, line):
        text = (line or "").strip()
        if not text:
            return None
        progress = re.match(r"\[(\d+)/(\d+)\]\s+(.*)", text)
        if progress:
            current, total, detail = progress.groups()
            if "Added rotated ellipse" in detail:
                return f"Generated layer {current}/{total}"
            if "Saved geometry checkpoint" in detail:
                return f"Saved JSON checkpoint {current}/{total}"
            if "Saved preview snapshot" in detail:
                return f"Updated preview {current}/{total}"
            if "Step completed" in detail:
                return None
            return None
        if text.startswith("Loaded image:"):
            return text
        if text.startswith("Settings:"):
            return text
        if text.startswith("OpenCL: Selected device"):
            return text
        if text.startswith("Scoring mode:"):
            return text
        if text in ("FINISHED",):
            return text
        if "error" in text.lower() or "failed" in text.lower() or "panic" in text.lower():
            return text
        return None

    def queue_generator_message(self, friendly, last_message):
        if not friendly or friendly == last_message:
            return last_message
        if friendly.startswith("Generated layer "):
            message = self._progress_with_eta(friendly)
            self.queue.put(("progress", message))
            self.queue.put(("log", message))
            return friendly
        if friendly == "FINISHED":
            self.queue.put(("progress", friendly))
        self.queue.put(("log", friendly))
        return friendly

    def _int_setting(self, setting, key, default=0):
        try:
            return int(str(setting.get("values", {}).get(key, default)).strip())
        except (TypeError, ValueError):
            return default

    def _log_generation_load_warning(self, setting):
        stop_at = self._int_setting(setting, "stopAt")
        random_samples = self._int_setting(setting, "randomSamples")
        mutated_samples = self._int_setting(setting, "mutatedSamples")
        max_resolution = self._int_setting(setting, "maxResolution")
        if random_samples >= 200000 or mutated_samples >= 8000 or max_resolution >= 2000:
            self.queue.put((
                "log",
                "High quality generation selected: "
                f"layers={stop_at}, randomSamples={random_samples}, "
                f"mutatedSamples={mutated_samples}, maxResolution={max_resolution}. "
                "The first layer can take a long time before progress appears.",
            ))

    def _generator_exit_message(self, returncode):
        if returncode in (3221225477, -1073741819):
            return (
                "GPU generator crashed with Windows access violation 0xC0000005. "
                "This is usually an OpenCL/GPU driver or generator runtime crash, not an import error. "
                "Try a lower preset, lower Max resolution / Random samples, update the GPU driver, "
                "or convert the source image to a normal PNG/JPG path and retry."
            )
        if returncode == 3221226505:
            return (
                "GPU generator crashed with Windows stack buffer overrun 0xC0000409. "
                "Try updating the GPU driver, lowering the preset, or converting the image to PNG/JPG."
            )
        return f"Generator exited with code {returncode}."

    def add_images(self):
        files = filedialog.askopenfilenames(
            title="Choose images",
            filetypes=[("Images", "*.png *.jpg *.jpeg *.bmp"), ("All files", "*.*")],
        )
        for item in files:
            path = Path(item)
            if path.exists() and path not in self.images:
                self.images.append(path)
        self._render_lists()
        if files:
            self.show_preview(render_source_image(Path(files[0])))

    def add_json(self):
        files = filedialog.askopenfilenames(
            title="Choose geometry JSON",
            filetypes=[("Geometry JSON", "*.json"), ("All files", "*.*")],
        )
        for item in files:
            path = Path(item)
            if path.exists() and path not in self.json_files:
                self.json_files.append(path)
        self._render_lists()
        if files:
            self.show_preview(render_geometry_json(Path(files[0])))

    def use_generated_outputs(self):
        for path in self.outputs:
            if path.exists() and path not in self.json_files:
                self.json_files.append(path)
        self._render_lists()
        self.log_line(f"Added {len(self.outputs)} generated JSON file(s) to import list.")

    def _preview_selected_image(self, _event=None):
        selection = self.image_list.curselection()
        if selection:
            self.show_preview(render_source_image(self.images[selection[0]]))

    def _preview_selected_json(self, _event=None):
        selection = self.json_list.curselection()
        if selection:
            self.show_preview(render_geometry_json(self.json_files[selection[0]]))

    def show_preview(self, data):
        if not data:
            message = tr(self.lang, "preview_unavailable")
            self.preview_label.config(image="", text=message, bg="#202020")
            self.preview_label.image = None
            if hasattr(self, "import_preview_label"):
                self.import_preview_label.config(image="", text=message, bg="#202020")
                self.import_preview_label.image = None
            return
        self.photo = data
        image = PhotoImage(data=data)
        self.preview_label.config(image=image, text="", bg="#202020")
        self.preview_label.image = image
        if hasattr(self, "import_preview_label"):
            import_image = PhotoImage(data=data)
            self.import_preview_label.config(image=import_image, text="", bg="#202020")
            self.import_preview_label.image = import_image

    def show_preview_file(self, path):
        try:
            image = PhotoImage(file=str(path))
        except Exception:
            self.show_preview(None)
            return
        self.photo = image
        self.preview_label.config(image=image, text="", bg="#202020")
        self.preview_label.image = image
        if hasattr(self, "import_preview_label"):
            import_image = PhotoImage(file=str(path))
            self.import_preview_label.config(image=import_image, text="", bg="#202020")
            self.import_preview_label.image = import_image

    def refresh_processes(self):
        self.processes = game_processes()
        values = [item["label"] for item in self.processes]
        if not values:
            values = [tr(self.lang, "no_game")]
        self.process_combo["values"] = values
        if self.processes:
            self.selected_pid.set(values[0])
            self.selected_game.set(self.processes[0]["profile"])
        else:
            self.selected_pid.set("")

    def selected_pid_value(self):
        raw = self.selected_pid.get()
        match = re.search(r"pid\s+(\d+)", raw, re.I)
        if match:
            return int(match.group(1))
        try:
            return int(raw.strip())
        except ValueError:
            return None

    def _pid_matches_game(self, pid, game):
        profile = PROFILES.get(game)
        if not pid or not profile:
            return False
        try:
            process_name = psutil.Process(pid).name().lower()
        except psutil.Error:
            return False
        return process_name in [name.lower() for name in profile.process_names]

    def ensure_live_game_pid(self):
        game = self.selected_game.get() or "fh6"
        pid = self.selected_pid_value()
        if self._pid_matches_game(pid, game):
            return pid
        if pid:
            self.log_line(f"Selected game process pid {pid} is no longer running; refreshing process list.")
        self.refresh_processes()
        game = self.selected_game.get() or game
        pid = self.selected_pid_value()
        if self._pid_matches_game(pid, game):
            return pid
        self.log_line("No live supported game process is selected. Start FH6, then click Refresh.")
        return None

    def stop_generate(self):
        with self.generation_lock:
            if not self.generation_running:
                self.log_line(tr(self.lang, "no_generation_running"))
                return
            proc = self.current_generator_proc
        self.log_line(tr(self.lang, "stopping_generation"))
        self.shutdown_event.set()
        if proc is not None:
            self._terminate_process(proc)
        self.status.set(tr(self.lang, "stopped"))

    def start_generate(self):
        with self.generation_lock:
            if self.generation_running:
                self.log_line("Generation is already running. Wait for it to finish or use Stop current generation.")
                return
            self.generation_running = True
        if not self.images:
            with self.generation_lock:
                self.generation_running = False
            self.log_line("No images selected.")
            return
        setting = self._effective_setting()
        if not setting:
            with self.generation_lock:
                self.generation_running = False
            self.log_line("No quality profile selected.")
            return
        if not GENERATOR_EXE.exists():
            with self.generation_lock:
                self.generation_running = False
            self.log_line(f"Missing generator: {GENERATOR_EXE}")
            return
        self.shutdown_event.clear()
        self._reset_generation_eta()
        self.progress_text.set("")
        self.status.set(tr(self.lang, "running"))
        if hasattr(self, "generate_button"):
            self.generate_button.config(state="disabled")
        if hasattr(self, "stop_generate_button"):
            self.stop_generate_button.config(state="normal")
        threading.Thread(target=self._generate_worker, args=(setting,), daemon=True).start()

    def _generate_worker(self, setting):
        try:
            self.queue.put(("log", f"Selected profile: {setting['path'].name}"))
            self._log_generation_load_warning(setting)
            for image_path in list(self.images):
                if self.shutdown_event.is_set():
                    self.queue.put(("status", tr(self.lang, "stopped")))
                    return
                self._reset_generation_eta()
                before = {path.resolve() for path in generated_jsons(image_path)}
                preview_path = generator_preview_path(image_path)
                if preview_path.exists():
                    try:
                        preview_path.unlink()
                    except OSError:
                        pass
                self.queue.put(("log", f"Generating: {image_path}"))
                self.queue.put(("preview", render_source_image(image_path)))
                flags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
                cmd = build_generator_command(image_path, setting)
                self._record_detail(f"GENERATOR COMMAND: {self._format_command(cmd)}")
                self.queue.put(("log", f"Running GPU generator with {setting['path'].name}"))
                if self.shutdown_event.is_set():
                    self.queue.put(("status", tr(self.lang, "stopped")))
                    return
                proc = self._popen_registered(
                    cmd,
                    cwd=ROOT,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    bufsize=1,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    creationflags=flags,
                )
                if proc is None:
                    self.queue.put(("status", tr(self.lang, "stopped")))
                    return
                with self.generation_lock:
                    self.current_generator_proc = proc

                last_preview = None
                last_preview_mtime = None
                last_generator_message = None
                output_queue = queue.Queue()

                def _read_generator_output():
                    try:
                        for raw_line in proc.stdout:
                            self._record_detail(f"GENERATOR RAW: {raw_line.rstrip()}")
                            output_queue.put(raw_line)
                    finally:
                        output_queue.put(None)

                reader = threading.Thread(target=_read_generator_output, daemon=True)
                reader.start()

                def _drain_generator_output():
                    nonlocal last_generator_message
                    while True:
                        try:
                            raw_line = output_queue.get_nowait()
                        except queue.Empty:
                            break
                        if raw_line is None:
                            continue
                        friendly = self.friendly_generator_line(raw_line)
                        last_generator_message = self.queue_generator_message(friendly, last_generator_message)

                try:
                    while proc.poll() is None:
                        if self.shutdown_event.is_set():
                            self._terminate_process(proc)
                            self.queue.put(("status", tr(self.lang, "stopped")))
                            return
                        _drain_generator_output()
                        preview_files = generated_preview_files(image_path)
                        if preview_files:
                            newest_preview = preview_files[0]
                            preview_mtime = newest_preview.stat().st_mtime
                            if preview_mtime != last_preview_mtime:
                                last_preview_mtime = preview_mtime
                                self.queue.put(("preview_file", newest_preview))
                        newest = generated_jsons(image_path)
                        if newest and newest[0] != last_preview:
                            last_preview = newest[0]
                        time.sleep(0.1)
                    if self.shutdown_event.is_set():
                        return
                    reader.join(timeout=1)
                    _drain_generator_output()
                finally:
                    self._unregister_process(proc)
                    with self.generation_lock:
                        if self.current_generator_proc is proc:
                            self.current_generator_proc = None
                if proc.returncode != 0:
                    self._record_detail(f"GENERATOR EXIT: {proc.returncode}")
                    self.queue.put(("log", self._generator_exit_message(proc.returncode)))
                    self.queue.put(("status", tr(self.lang, "failed")))
                    return
                self._record_detail("GENERATOR EXIT: 0")
                after = generated_jsons(image_path)
                new_outputs = best_geometry_jsons([path for path in after if path.resolve() not in before])
                if not new_outputs and after:
                    new_outputs = best_geometry_jsons(after[:1])
                if not new_outputs:
                    self.queue.put(("log", "Generator finished but no JSON output was found."))
                    self.queue.put(("status", tr(self.lang, "failed")))
                    return
                for output in new_outputs:
                    if output not in self.outputs:
                        self.outputs.append(output)
                    if output not in self.json_files:
                        self.json_files.append(output)
                    self.queue.put(("log", f"Generated: {output}"))
                    preview_files = generated_preview_files(image_path)
                    if preview_files:
                        self.queue.put(("preview_file", preview_files[0]))
                    else:
                        self.queue.put(("preview", render_geometry_json(output)))
            self.queue.put(("render_lists", None))
            self.queue.put(("status", tr(self.lang, "done")))
        except Exception as exc:
            self.queue.put(("log", f"Generator failed: {exc}"))
            self.queue.put(("status", tr(self.lang, "failed")))
        finally:
            self.queue.put(("generation_done", None))

    def open_output_folder(self):
        folder = None
        if self.outputs:
            folder = self.outputs[-1].parent
        elif self.images:
            folder = self.images[-1].parent
        if folder and folder.exists():
            os.startfile(folder)

    def run_subprocess(self, cmd, timeout=None):
        self._record_detail(f"HELPER COMMAND: {self._format_command(cmd)}")
        self.queue.put(("log", self._friendly_command_name(cmd)))
        flags = subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0
        env = os.environ.copy()
        env.update({"FORZA_PAINTER_NO_ELEVATE": "1", "FORZA_PAINTER_NO_PAUSE": "1"})
        if self.shutdown_event.is_set():
            self._record_detail("HELPER EXIT: 130 before start")
            return 130
        proc = self._popen_registered(
            [str(x) for x in cmd],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            creationflags=flags,
            env=env,
        )
        if proc is None:
            self._record_detail("HELPER EXIT: 130 no process")
            return 130
        started = time.time()
        try:
            while True:
                if self.shutdown_event.is_set():
                    self._terminate_process(proc)
                    self._record_detail("HELPER EXIT: 130 stopped")
                    return 130
                line = proc.stdout.readline()
                if line:
                    self._record_detail(f"HELPER RAW: {line.rstrip()}")
                    friendly = self._friendly_subprocess_line(line.rstrip())
                    if friendly:
                        self.queue.put(("log", friendly))
                if proc.poll() is not None:
                    break
                if timeout and time.time() - started > timeout:
                    self._terminate_process(proc)
                    self._record_detail(f"HELPER EXIT: 124 timeout after {timeout} seconds")
                    self.queue.put(("log", f"Timed out after {timeout} seconds."))
                    return 124
                time.sleep(0.05)
            if self.shutdown_event.is_set():
                self._record_detail("HELPER EXIT: 130 stopped after process exit")
                return 130
            for line in proc.stdout.read().splitlines():
                self._record_detail(f"HELPER RAW: {line.rstrip()}")
                friendly = self._friendly_subprocess_line(line.rstrip())
                if friendly:
                    self.queue.put(("log", friendly))
            self._record_detail(f"HELPER EXIT: {proc.returncode}")
            return proc.returncode
        finally:
            self._unregister_process(proc)

    def _friendly_command_name(self, cmd):
        joined = " ".join(str(x) for x in cmd)
        if "fh6_probe.py" in joined and "--auto-locate" in joined:
            return tr(self.lang, "locating")
        if "main.py" in joined:
            return tr(self.lang, "importing")
        return "Starting helper..."

    def _check_json_layer_fit(self, json_path, layer_count):
        try:
            from generator_backend import geometry_shape_count
            json_layers = geometry_shape_count(json_path)
            template_layers = int(layer_count)
        except Exception:
            return
        usable_layers = max(0, template_layers - 4)
        if json_layers and template_layers and json_layers > usable_layers:
            self.queue.put(("log", f"{tr(self.lang, 'json_needs_more_template_layers')} JSON={json_layers}, template={template_layers}, usable={usable_layers}"))
        if json_layers and usable_layers and json_layers < usable_layers * 0.75:
            self.queue.put(("log", f"{tr(self.lang, 'json_too_small')} JSON={json_layers}, usable={usable_layers}"))

    def _friendly_subprocess_line(self, line):
        if not line:
            return None
        raw = line.strip()
        lower = raw.lower()
        noisy_parts = (
            "base:",
            "candidate score=",
            "layout candidate",
            "table[",
            "ptr=0x",
            "count=0x",
            "tablefield=",
            "wrote fh6 session location",
            "fh6 layout-count scan checked",
            "process: forzahorizon",
            "current values:",
            "loaded ",
            "descriptor @",
            "info found:",
            "vtp found:",
        )
        if any(part in lower for part in noisy_parts):
            return None
        if "fast fh6 layer group candidates:" in lower:
            return tr(self.lang, "located")
        if "no safe fh6 layer group" in lower:
            return tr(self.lang, "safe_stop")
        if "auto-locating fh6 layer count/table" in lower:
            return tr(self.lang, "locating")
        if "cliverylayer table found" in lower:
            return tr(self.lang, "located")
        if "forza horizon 6 detected" in lower:
            return raw
        if raw.startswith("Writing layer") or raw == "DONE!" or raw.startswith("The ideal background color"):
            return raw
        if "openprocess" in lower or "error" in lower or "failed" in lower or "traceback" in lower:
            return raw
        if raw.startswith("<class 'SystemExit'>") or raw.startswith("SystemExit: 0"):
            return None
        return raw

    def start_auto_locate(self):
        pid = self.ensure_live_game_pid()
        layer_count = self.layer_count.get().strip()
        if not pid or not layer_count:
            self.log_line("PID and template layer count are required.")
            return
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=self._auto_locate_worker, args=(pid, layer_count), daemon=True).start()

    def _auto_locate_worker(self, pid, layer_count):
        clear_session_location()
        cmd = [
            sys.executable,
            APP_DIR / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(layer_count),
            "--auto-locate",
            "--write-session",
            SESSION_PATH,
            "--limit-mb",
            str(MEMORY_SNAPSHOT_LIMIT_MB),
            "--max-matches",
            "500000",
            "--inspect-radius",
            "0x800",
            "--max-seconds",
            str(FH6_AUTO_LOCATE_MAX_SECONDS),
        ]
        code = self.run_subprocess(cmd, timeout=FH6_AUTO_LOCATE_TIMEOUT_SECONDS)
        located = False
        if code == 0 and SESSION_PATH.exists():
            session = load_session_location()
            if session_matches_current_import(session, self.selected_game.get() or "fh6", pid, layer_count):
                self.queue.put(("log", tr(self.lang, "located")))
                located = True
        self.queue.put(("status", tr(self.lang, "done") if located else tr(self.lang, "failed")))
        return located

    def start_import(self):
        if not self.json_files:
            self.log_line("No JSON files selected.")
            return
        pid = self.ensure_live_game_pid()
        if not pid:
            return
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=self._import_worker, args=(pid,), daemon=True).start()

    def _import_worker(self, pid):
        game = self.selected_game.get() or "fh6"
        count_address = parse_hex_or_empty(self.count_address.get())
        table_address = parse_hex_or_empty(self.table_address.get())
        layer_count = self.layer_count.get().strip()
        if not count_address and not table_address and game == "fh6":
            session = load_session_location()
            if session_matches_current_import(session, game, pid, layer_count):
                pid = int(session["pid"])
                count_address = "0x{:x}".format(int(session["count_address"]))
                table_address = "0x{:x}".format(int(session["table_address"]))
                self.queue.put(("log", tr(self.lang, "located")))
            elif pid and layer_count:
                self.queue.put(("log", tr(self.lang, "locating")))
                located = self._auto_locate_worker(pid, layer_count)
                session = load_session_location()
                if located and session_matches_current_import(session, game, pid, layer_count):
                    count_address = "0x{:x}".format(int(session["count_address"]))
                    table_address = "0x{:x}".format(int(session["table_address"]))
                else:
                    self.queue.put(("status", tr(self.lang, "failed")))
                    return
        for path in list(self.json_files):
            if game == "fh6" and layer_count:
                self._check_json_layer_fit(path, layer_count)
            cmd = [sys.executable, APP_DIR / "main.py", "--game", game, "--no-preview"]
            if pid:
                cmd.extend(["--pid", str(pid)])
            if count_address:
                cmd.extend(["--layer-count-address", count_address])
            if table_address:
                cmd.extend(["--layer-table-address", table_address])
            if game == "fh6" and layer_count:
                cmd.extend(["--layer-count-value", str(layer_count)])
            cmd.append(path)
            code = self.run_subprocess(cmd)
            if code != 0:
                self.queue.put(("status", tr(self.lang, "failed")))
                return
        self.queue.put(("status", tr(self.lang, "done")))

    def start_diagnose(self):
        pid = self.ensure_live_game_pid()
        cmd = [sys.executable, APP_DIR / "main.py", "--game", self.selected_game.get() or "fh6", "--diagnose"]
        if pid:
            cmd.extend(["--pid", str(pid)])
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 120), daemon=True).start()

    def start_save_snapshot(self):
        pid = self.ensure_live_game_pid()
        count = self.snapshot_count.get().strip() or self.layer_count.get().strip()
        if not pid or not count:
            self.log_line("PID and snapshot layer count are required.")
            return
        output_path = PROBE_DIR / f"memory-count-{count}.jsonl"
        cmd = [
            sys.executable,
            APP_DIR / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(count),
            "--save-memory-snapshot",
            output_path,
            "--limit-mb",
            str(MEMORY_SNAPSHOT_LIMIT_MB),
        ]
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 360), daemon=True).start()

    def start_compare_snapshot(self):
        pid = self.ensure_live_game_pid()
        previous = self.snapshot_count.get().strip()
        current = self.current_count.get().strip() or self.layer_count.get().strip()
        if not pid or not previous or not current:
            self.log_line("PID, snapshot layer count, and current layer count are required.")
            return
        snapshot_path = PROBE_DIR / f"memory-count-{previous}.jsonl"
        candidates_path = PROBE_DIR / f"memory-count-{previous}-to-{current}-candidates.json"
        intersect_path = PROBE_DIR / f"memory-count-{int(previous) - 1}-to-{previous}-candidates.json"
        cmd = [
            sys.executable,
            APP_DIR / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(current),
            "--compare-memory-snapshot",
            snapshot_path,
            "--write-candidates",
            candidates_path,
            "--max-matches",
            "50000",
        ]
        if intersect_path.exists():
            cmd.extend(["--intersect-candidates", intersect_path])
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 360), daemon=True).start()

    def start_inspect_table(self):
        pid = self.ensure_live_game_pid()
        table = self.inspect_table_value.get().strip()
        count = self.layer_count.get().strip()
        if not pid or not table or not count:
            self.log_line("PID, layer count, and table address are required.")
            return
        cmd = [
            sys.executable,
            APP_DIR / "fh6_probe.py",
            "--game",
            self.selected_game.get() or "fh6",
            "--pid",
            str(pid),
            "--layer-count",
            str(count),
            "--inspect-table",
            table,
            "--inspect-layers",
            "12",
        ]
        self.status.set(tr(self.lang, "running"))
        threading.Thread(target=lambda: self._run_command_worker(cmd, 60), daemon=True).start()

    def _run_command_worker(self, cmd, timeout):
        code = self.run_subprocess(cmd, timeout=timeout)
        self.queue.put(("status", tr(self.lang, "done") if code == 0 else tr(self.lang, "failed")))

    def _poll_queue(self):
        if self.closed:
            return
        while True:
            try:
                kind, payload = self.queue.get_nowait()
            except queue.Empty:
                break
            if kind == "log":
                self.log_line(payload)
            elif kind == "progress":
                self.progress_text.set(payload)
            elif kind == "status":
                self.status.set(payload)
            elif kind == "generation_done":
                stopped = self.shutdown_event.is_set()
                with self.generation_lock:
                    self.generation_running = False
                    self.current_generator_proc = None
                if hasattr(self, "generate_button"):
                    self.generate_button.config(state="normal")
                if hasattr(self, "stop_generate_button"):
                    self.stop_generate_button.config(state="disabled")
                if stopped and not self.closed:
                    self.progress_text.set(tr(self.lang, "generation_stopped"))
                    self.status.set(tr(self.lang, "stopped"))
                    self.log_line(tr(self.lang, "generation_stopped"))
            elif kind == "preview":
                self.show_preview(payload)
            elif kind == "preview_file":
                self.show_preview_file(payload)
            elif kind == "render_lists":
                self._render_lists()
        if not self.closed:
            self.root.after(100, self._poll_queue)

    def run(self):
        self.root.mainloop()


def main():
    parser = argparse.ArgumentParser(description=f"Standalone {APP_DISPLAY_NAME} desktop app.")
    parser.add_argument("--version", action="version", version=f"{APP_DISPLAY_NAME} {__version__}")
    parser.add_argument("images", nargs="*", help="Optional image files to preload.")
    args = parser.parse_args()
    App(args.images).run()


if __name__ == "__main__":
    main()
